### ISSUE TITLE
Unable to use arbitrary extensions for partials

### ISSUE THREAD

**Issue by fidian** [shannonmoeller/handlebars-wax#13]
I'm trying to load handlebar partials into both metalsmith-layouts and metalsmith-hbt-md because I first process markdown as mustache, then convert to HTML, then insert into the layout which is also mustache.

It appears that you're using `require(partialFilename)`. When it's HTML, I get the following error:

    /home/user/project/layout/partials/content.html:1
    (function (exports, require, module, __filename, __dirname) { <div class="D(tbc) W(100%)">

HTML isn't valid JS, so the cause of the error is obvious. Can arbitrary extensions be made to work?

**Comment by shannonmoeller** [comment]
I've added an `extensions` option which now defaults to `['.handlebars', '.hbs', '.html']`. Released as v6.0.0.

**Comment by fidian** [comment]
Wow, thanks for that amazingly fast turnaround!!
