### ISSUE TITLE
Partial names on Windows machine

### ISSUE THREAD

**Issue by icehaunter** [shannonmoeller/handlebars-wax#5]
If you add partial folder and load it (at least with gulp-hb), partial names look like an absolute path from C: instead of just "partials/layouts". The problem lies in keygenPartial function, as it assumes forward slashes in the path. Problem is solvable by replacing
`var shortPath = file.path.replace(file.base + '/', '');`
with
`var shortPath = file.path.replace(/\\/g, '/').replace(file.base.replace(/\\/g, '/') + '/', '');`

**Comment by shannonmoeller** [comment]
Thanks for reporting the issue. Published fix as v3.4.2.

**Comment by gligoran** [comment]
@shannonmoeller: This isn't completely fixed.

You still use the current OS's native separators when you're trying to get `shortPath` by using `file.base`:

```js
var fullPath = file.path.replace(PATH_SEPARATORS, PATH_SEPARATOR);
var shortPath = fullPath.replace(file.base + PATH_SEPARATOR, '');
```

You should do the same replacement on `file.base`. Something like this:

```js
var fullPath = file.path.replace(PATH_SEPARATORS, PATH_SEPARATOR);
var fileBase = file.base.replace(PATH_SEPARATORS, PATH_SEPARATOR);
var shortPath = fullPath.replace(fileBase + PATH_SEPARATOR, ''); //NOTE: uses the new variable
```

**Comment by shannonmoeller** [comment]
<img src="https://cloud.githubusercontent.com/assets/155164/13190516/8dffbc3a-d72b-11e5-9775-c5ec0b4427bf.png" alt="facepalm" width="320" />

And v3.4.3 coming at you. Thanks, @gligoran.

**Comment by gligoran** [comment]
![picard-full-of-win1-e1309226314822](https://cloud.githubusercontent.com/assets/444829/13190764/80f299b6-d75f-11e5-8269-181786d922a6.jpg)

That was super fast. Thanks :+1:
