### ISSUE TITLE
Yaml data files

### ISSUE THREAD

**Issue by mendlik** [shannonmoeller/handlebars-wax#6]
Hi, thanks for you work. This module is very helpful.

I have a question. Is it possible to extend `handlebars-wax` to use yaml (and/or json5) in data files?

Regards

**Comment by shannonmoeller** [comment]
I considered adding a hook for this (open for discussion), but as Node already has support for [overloading `require()`](https://nodejs.org/api/all.html#all_require_extensions), I felt it would be redundant.

```js
require('json5/lib/require');
require('yamlify/register');

var handlebars = require('handlebars');
var handlebarsWax = require('handlebars-wax');

var wax = handlebarsWax(handlebars)
    .data('./**/*.{json5,yml}');

// Good to go.
```

**Comment by mendlik** [comment]
Perfect. Thank you very much.

**Comment by shannonmoeller** [comment]
My pleasure!

**Comment by mendlik** [comment]
I have one more concern about this issue.

What about a situation when `handlebars-wax` is executed by a `gulp.watch(...)`. Then if the data is changed it will not be updated in `handlebars-wax` because it's cached in `require`.
I created a [branch that introduces failing tests](https://github.com/mendlik/handlebars-wax/tree/feature/issue-6-data-formats-and-caching).

You could introduce a caching option or add a hook, as you already mentioned.

Please, don't get me wrong. This module is still super handy :)

**Comment by shannonmoeller** [comment]
Already taken care of! Just not documented at this level. The underlying `require-glob` module has a [`bustCache` option](https://github.com/shannonmoeller/require-glob#bustcache). It defaults to [`true` in `gulp-hb`](https://github.com/shannonmoeller/gulp-hb#hboptions-transformstream).

```js
var wax = handlebarsWax(handlebars, {
    bustCache: true
});
```

I'll update the README.

**Comment by shannonmoeller** [comment]
Thanks for creating the tests! I'm sorry that my omission in the README wasted your time!

**Comment by shannonmoeller** [comment]
I'm thinking about switching the `bustCache` default to `true` at this level. Having a hard time thinking of a situation where I wouldn't want that to happen with this lib. Thoughts?

**Comment by mendlik** [comment]
Thanks again for a prompt and precise reply.

It wasn't a waste of time. I could read the documentation more thoroughly.
Moreover, diving in your code I learnt new things.

IMHO changing `bustCache` default to `true` is a good idea.
