### ISSUE TITLE
Templating errors

### ISSUE THREAD

**Issue by mendlik** [shannonmoeller/handlebars-wax#7]
Hi, it's me again (https://github.com/shannonmoeller/handlebars-wax/issues/6).

Just one more question. Is it possible to produce an error when partial used in template was not found? I caught myself checking resulting html file multiple times. 

Regards

**Comment by shannonmoeller** [comment]
Hmm. Could have sworn I had a test case for that. I'll whip one up. In the meantime, is it possible the error is getting swallowed somehow? Perhaps by a Promise?

**Comment by mendlik** [comment]
Yes, it is possible. I'm using https://github.com/shannonmoeller/gulp-hb that wraps https://github.com/shannonmoeller/handlebars-wax. Maybe it's a problem in gulp-hb?

**Comment by shannonmoeller** [comment]
Oh, cool. It's possible. I'll make sure to get a test in there too.

**Comment by mendlik** [comment]
Again, thank you very much.

**Comment by shannonmoeller** [comment]
I've added some tests and confirmed that errors throw by handlebars are not being swallowed by this lib. They raise like they should and can be handled with try/catch, etc. Closing this. Will continue looking into gulp-hb.
