### ISSUE TITLE
register partials fail for case sensitive path in my pc win10

### ISSUE THREAD

**Issue by charlenezell** [shannonmoeller/handlebars-wax#9]
the default partial parsing method is not work in my terminal integrated in vscode 
for the following replacement not work
```javascript
var shortPath = fullPath.replace(basePath, '');
```
fullpath is **C:/xxxx/xx.hbs**
and the basePath in my env is **c:/xxxx/**
so my workaround is your config option  like this:
```javascript
 var shortPath = fullPath.replace(new RegExp(basePath,"i"), '');
```
maybe you should fix this 
im using your gulp-hbs and was trap by this

**Comment by shannonmoeller** [comment]
Fixed and released as 4.0.1. Thanks!
